// <auto-generated />
using System;
using CoachAssist.Core.Enums;
using CoachAssist.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoachAssist.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "aanvraagstatus", new[] { "geweigerd", "goedgekeurd", "in afwachting" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "aanvraagstatus", "aanvraag_status", new[] { "in afwachting", "goedgekeurd", "geweigerd" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "gebruikersrol", new[] { "admin", "coach", "speler" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "gebruikersrol", "gebruiker_rol", new[] { "admin", "coach", "speler" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "opstelling_positie", new[] { "Aanvallende middenvelder", "Centrale middenvelder", "Centrale verdediger", "Verdedigende middenvelder", "keeper", "linksback", "linksbuiten", "rechtsback", "rechtsbuiten", "schaduwspits", "spits" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "opstelling_positie", "opstelling_positie", new[] { "keeper", "rechtsback", "linksback", "Centrale verdediger", "Verdedigende middenvelder", "Centrale middenvelder", "Aanvallende middenvelder", "rechtsbuiten", "linksbuiten", "spits", "schaduwspits" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trainingstatus", new[] { "afgelast", "gepland", "uitgesteld" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trainingstatus", "training_status", new[] { "gepland", "afgelast", "uitgesteld" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vaste_positie", new[] { "Niet gespecificeerd", "aanvaller", "keeper", "middenvelder", "verdediger" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vaste_positie", "vaste_positie", new[] { "keeper", "verdediger", "middenvelder", "aanvaller", "Niet gespecificeerd" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "wedstrijdstatus", new[] { "geannuleerd", "gepland", "gespeeld", "uitgesteld" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "wedstrijdstatus", "wedstrijd_status", new[] { "gepland", "gespeeld", "uitgesteld", "geannuleerd" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoachAssist.Core.Entities.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("clubid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClubId"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naam");

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stad");

                    b.HasKey("ClubId");

                    b.HasIndex("Naam")
                        .IsUnique();

                    b.ToTable("club", (string)null);
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.ClubAanvraag", b =>
                {
                    b.Property<int>("AanvraagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("aanvraagid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AanvraagId"));

                    b.Property<int>("ClubId")
                        .HasColumnType("integer")
                        .HasColumnName("clubid");

                    b.Property<DateTime?>("DatumAanvraag")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datumaanvraag");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("integer")
                        .HasColumnName("gebruikerid");

                    b.Property<AanvraagStatus>("Status")
                        .HasColumnType("aanvraagstatus")
                        .HasColumnName("status");

                    b.HasKey("AanvraagId");

                    b.HasIndex("ClubId");

                    b.HasIndex("GebruikerId", "ClubId")
                        .IsUnique();

                    b.ToTable("clubaanvraag", (string)null);
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Gebruiker", b =>
                {
                    b.Property<int>("GebruikerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gebruikerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GebruikerId"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("achternaam");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<GebruikerRol>("Rol")
                        .HasColumnType("gebruikersrol")
                        .HasColumnName("rol");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("voornaam");

                    b.HasKey("GebruikerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("gebruiker", (string)null);
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Opstelling", b =>
                {
                    b.Property<int>("OpstellingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("opstellingid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OpstellingId"));

                    b.Property<string>("Formatie")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("formatie");

                    b.Property<int?>("WedstrijdId")
                        .HasColumnType("integer")
                        .HasColumnName("wedstrijdid");

                    b.HasKey("OpstellingId");

                    b.HasIndex("WedstrijdId")
                        .IsUnique();

                    b.ToTable("opstelling", (string)null);
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.OpstellingSpeler", b =>
                {
                    b.Property<int>("OpstellingSpelerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("opstellingspelerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OpstellingSpelerId"));

                    b.Property<int>("OpstellingId")
                        .HasColumnType("integer")
                        .HasColumnName("opstellingid");

                    b.Property<OpstellingPositie>("PositieNaam")
                        .HasColumnType("opstelling_positie")
                        .HasColumnName("positienaam");

                    b.Property<int>("SpelerId")
                        .HasColumnType("integer")
                        .HasColumnName("spelerid");

                    b.Property<int?>("VeldPositieX")
                        .HasColumnType("integer")
                        .HasColumnName("veldpositiex");

                    b.Property<int?>("VeldPositieY")
                        .HasColumnType("integer")
                        .HasColumnName("veldpositiey");

                    b.HasKey("OpstellingSpelerId");

                    b.HasIndex("SpelerId");

                    b.HasIndex("OpstellingId", "SpelerId")
                        .IsUnique();

                    b.ToTable("opstellingspeler", (string)null);
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Speler", b =>
                {
                    b.Property<int>("SpelerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("spelerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpelerId"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("achternaam");

                    b.Property<int?>("GebruikerId")
                        .HasColumnType("integer")
                        .HasColumnName("gebruikerid");

                    b.Property<int?>("Rugnummer")
                        .HasColumnType("integer")
                        .HasColumnName("rugnummer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamid");

                    b.Property<VastePositie?>("VastePositie")
                        .HasColumnType("vaste_positie")
                        .HasColumnName("vastepositie");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("voornaam");

                    b.HasKey("SpelerId");

                    b.HasIndex("GebruikerId")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("speler", (string)null);
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.SpelerStatistiek", b =>
                {
                    b.Property<int>("StatistiekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("statistiekid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatistiekId"));

                    b.Property<int?>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<int?>("GeleKaarten")
                        .HasColumnType("integer")
                        .HasColumnName("gelekaarten");

                    b.Property<int?>("GespeeldeMinuten")
                        .HasColumnType("integer")
                        .HasColumnName("gespeeldeminuten");

                    b.Property<int?>("Goals")
                        .HasColumnType("integer")
                        .HasColumnName("goals");

                    b.Property<int?>("RodeKaarten")
                        .HasColumnType("integer")
                        .HasColumnName("rodekaarten");

                    b.Property<int>("SpelerId")
                        .HasColumnType("integer")
                        .HasColumnName("spelerid");

                    b.Property<int>("WedstrijdId")
                        .HasColumnType("integer")
                        .HasColumnName("wedstrijdid");

                    b.HasKey("StatistiekId");

                    b.HasIndex("WedstrijdId");

                    b.HasIndex("SpelerId", "WedstrijdId")
                        .IsUnique();

                    b.ToTable("spelerstatistiek", (string)null);
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("teamid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamId"));

                    b.Property<int>("ClubId")
                        .HasColumnType("integer")
                        .HasColumnName("clubid");

                    b.Property<int?>("CoachId")
                        .HasColumnType("integer")
                        .HasColumnName("coachid");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naam");

                    b.Property<string>("Seizoen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seizoen");

                    b.HasKey("TeamId");

                    b.HasIndex("ClubId");

                    b.HasIndex("CoachId");

                    b.HasIndex("Naam", "Seizoen", "ClubId")
                        .IsUnique();

                    b.ToTable("team", (string)null);
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.TeamAanvraag", b =>
                {
                    b.Property<int>("AanvraagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("aanvraagid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AanvraagId"));

                    b.Property<DateTime?>("DatumAanvraag")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datumaanvraag");

                    b.Property<int>("SpelerId")
                        .HasColumnType("integer")
                        .HasColumnName("spelerid");

                    b.Property<AanvraagStatus>("Status")
                        .HasColumnType("aanvraagstatus")
                        .HasColumnName("status");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamid");

                    b.HasKey("AanvraagId");

                    b.HasIndex("TeamId");

                    b.HasIndex("SpelerId", "TeamId")
                        .IsUnique();

                    b.ToTable("teamaanvraag", (string)null);
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Terrein", b =>
                {
                    b.Property<int>("TerreinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("terreinid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TerreinId"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adres");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer")
                        .HasColumnName("clubid");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naam");

                    b.HasKey("TerreinId");

                    b.HasIndex("ClubId");

                    b.HasIndex("Naam", "ClubId")
                        .IsUnique();

                    b.ToTable("terrein", (string)null);
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("trainingid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrainingId"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("date")
                        .HasColumnName("datum");

                    b.Property<TimeSpan>("EindTijd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("eindtijd");

                    b.Property<string>("Opmerking")
                        .HasColumnType("text")
                        .HasColumnName("opmerking");

                    b.Property<TimeSpan>("StartTijd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starttijd");

                    b.Property<TrainingStatus>("Status")
                        .HasColumnType("trainingstatus")
                        .HasColumnName("status");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamid");

                    b.Property<int>("TerreinId")
                        .HasColumnType("integer")
                        .HasColumnName("terreinid");

                    b.HasKey("TrainingId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TerreinId");

                    b.ToTable("training", (string)null);
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.TrainingAanwezigheid", b =>
                {
                    b.Property<int>("AanwezigheidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("aanwezigheidid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AanwezigheidId"));

                    b.Property<bool>("Aanwezig")
                        .HasColumnType("boolean")
                        .HasColumnName("aanwezig");

                    b.Property<string>("Reden")
                        .HasColumnType("text")
                        .HasColumnName("reden");

                    b.Property<int>("SpelerId")
                        .HasColumnType("integer")
                        .HasColumnName("spelerid");

                    b.Property<int>("TrainingId")
                        .HasColumnType("integer")
                        .HasColumnName("trainingid");

                    b.HasKey("AanwezigheidId");

                    b.HasIndex("SpelerId");

                    b.HasIndex("TrainingId", "SpelerId")
                        .IsUnique();

                    b.ToTable("trainingaanwezigheid", (string)null);
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Wedstrijd", b =>
                {
                    b.Property<int>("WedstrijdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wedstrijdid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WedstrijdId"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("date")
                        .HasColumnName("datum");

                    b.Property<string>("Opmerking")
                        .HasColumnType("text")
                        .HasColumnName("opmerking");

                    b.Property<TimeSpan>("StartTijd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starttijd");

                    b.Property<WedstrijdStatus>("Status")
                        .HasColumnType("wedstrijdstatus")
                        .HasColumnName("status");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamid");

                    b.Property<string>("Tegenstander")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tegenstander");

                    b.Property<int>("TerreinId")
                        .HasColumnType("integer")
                        .HasColumnName("terreinid");

                    b.Property<int?>("ThuisScore")
                        .HasColumnType("integer")
                        .HasColumnName("thuisscore");

                    b.Property<int?>("UitScore")
                        .HasColumnType("integer")
                        .HasColumnName("uitscore");

                    b.HasKey("WedstrijdId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TerreinId");

                    b.ToTable("wedstrijd", (string)null);
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.ClubAanvraag", b =>
                {
                    b.HasOne("CoachAssist.Core.Entities.Club", "Club")
                        .WithMany("Aanvragen")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachAssist.Core.Entities.Gebruiker", "Gebruiker")
                        .WithMany()
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Opstelling", b =>
                {
                    b.HasOne("CoachAssist.Core.Entities.Wedstrijd", "Wedstrijd")
                        .WithOne("Opstelling")
                        .HasForeignKey("CoachAssist.Core.Entities.Opstelling", "WedstrijdId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Wedstrijd");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.OpstellingSpeler", b =>
                {
                    b.HasOne("CoachAssist.Core.Entities.Opstelling", "Opstelling")
                        .WithMany("Spelers")
                        .HasForeignKey("OpstellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachAssist.Core.Entities.Speler", "Speler")
                        .WithMany("Opstellingen")
                        .HasForeignKey("SpelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opstelling");

                    b.Navigation("Speler");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Speler", b =>
                {
                    b.HasOne("CoachAssist.Core.Entities.Gebruiker", "Gebruiker")
                        .WithOne("Speler")
                        .HasForeignKey("CoachAssist.Core.Entities.Speler", "GebruikerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoachAssist.Core.Entities.Team", "Team")
                        .WithMany("Spelers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruiker");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.SpelerStatistiek", b =>
                {
                    b.HasOne("CoachAssist.Core.Entities.Speler", "Speler")
                        .WithMany("Statistieken")
                        .HasForeignKey("SpelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachAssist.Core.Entities.Wedstrijd", "Wedstrijd")
                        .WithMany("Statistieken")
                        .HasForeignKey("WedstrijdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speler");

                    b.Navigation("Wedstrijd");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Team", b =>
                {
                    b.HasOne("CoachAssist.Core.Entities.Club", "Club")
                        .WithMany("Teams")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachAssist.Core.Entities.Gebruiker", "Coach")
                        .WithMany("GecoachteTeams")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Club");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.TeamAanvraag", b =>
                {
                    b.HasOne("CoachAssist.Core.Entities.Speler", "Speler")
                        .WithMany()
                        .HasForeignKey("SpelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachAssist.Core.Entities.Team", "Team")
                        .WithMany("Aanvragen")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speler");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Terrein", b =>
                {
                    b.HasOne("CoachAssist.Core.Entities.Club", "Club")
                        .WithMany("Terreinen")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Training", b =>
                {
                    b.HasOne("CoachAssist.Core.Entities.Team", "Team")
                        .WithMany("Trainingen")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachAssist.Core.Entities.Terrein", "Terrein")
                        .WithMany("Trainingen")
                        .HasForeignKey("TerreinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Terrein");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.TrainingAanwezigheid", b =>
                {
                    b.HasOne("CoachAssist.Core.Entities.Speler", "Speler")
                        .WithMany("Aanwezigheden")
                        .HasForeignKey("SpelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachAssist.Core.Entities.Training", "Training")
                        .WithMany("Aanwezigheden")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speler");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Wedstrijd", b =>
                {
                    b.HasOne("CoachAssist.Core.Entities.Team", "Team")
                        .WithMany("Wedstrijden")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachAssist.Core.Entities.Terrein", "Terrein")
                        .WithMany("Wedstrijden")
                        .HasForeignKey("TerreinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Terrein");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Club", b =>
                {
                    b.Navigation("Aanvragen");

                    b.Navigation("Teams");

                    b.Navigation("Terreinen");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Gebruiker", b =>
                {
                    b.Navigation("GecoachteTeams");

                    b.Navigation("Speler");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Opstelling", b =>
                {
                    b.Navigation("Spelers");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Speler", b =>
                {
                    b.Navigation("Aanwezigheden");

                    b.Navigation("Opstellingen");

                    b.Navigation("Statistieken");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Team", b =>
                {
                    b.Navigation("Aanvragen");

                    b.Navigation("Spelers");

                    b.Navigation("Trainingen");

                    b.Navigation("Wedstrijden");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Terrein", b =>
                {
                    b.Navigation("Trainingen");

                    b.Navigation("Wedstrijden");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Training", b =>
                {
                    b.Navigation("Aanwezigheden");
                });

            modelBuilder.Entity("CoachAssist.Core.Entities.Wedstrijd", b =>
                {
                    b.Navigation("Opstelling");

                    b.Navigation("Statistieken");
                });
#pragma warning restore 612, 618
        }
    }
}
