services:
  - type: web
    name: bachelor-thesis-padict-api
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: COACHASSIST_JWT_SECRET
        sync: false
